### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')     at HTMLDivElement.createModalContent (

### ISSUE THREAD

**Issue by PhocaCz** [dgrammatiko/mod_child_export#2]
Hi, testing now, when clicking on "Select Child Template", I get:

```
default.min.js?27b9f…d642f9dd39564f189:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at HTMLDivElement.createModalContent (default.min.js?27b9f…9dd39564f189:1:2172)
createModalContent	@	default.min.js?27b9f…d642f9dd39564f189:1
await in createModalContent (async)		
trigger	@	dom.min.js?5.1.3:1
show	@	modal.min.js?5.1.3:1
toggle	@	modal.min.js?5.1.3:1
(anonymous)	@	modal.min.js?5.1.3:1
o	@	dom.min.js?5.1.3:1
```
![img](https://i.imgur.com/rKqECGg.png)

Child template exist:

![img](https://i.imgur.com/DFoBPhr.png)

**Comment by dgrammatiko** [comment]
What browser?

**Comment by PhocaCz** [comment]
Google Chrome
Version 112.0.5615.165 (Official Build) (64-bit)

**Comment by dgrammatiko** [comment]
Can you test https://github.com/dgrammatiko/mod_child_export/releases/tag/v0.0.03

**Comment by PhocaCz** [comment]
Now, there is no error, everything is OK, but it just does not find the child templates:

![img](https://i.imgur.com/pTS00sl.png)

**Comment by PhocaCz** [comment]
![img](https://i.imgur.com/KoQEUCQ.png)

**Comment by dgrammatiko** [comment]
Aha, try deleting the `administrator/cache/autoload_psr4.php`. Also this won't work on < 4.3.0 (I think the namespaces for modules are not supported on earlier J versions)

**Comment by PhocaCz** [comment]
Updated to 4.3.1, removed autoload_ps4.php and still no success.

![gif](https://i.imgur.com/21Mjplg.gif)

**Comment by PhocaCz** [comment]
BTW:
```
{success: false, message: "The file at mod_childexport/helper.php does not exist.", messages: null,…}
data
: 
null
message
: 
"The file at mod_childexport/helper.php does not exist."
messages
: 
null
success
: 
false
```
There is no helper.php file in mod_childexport folder.

**Comment by dgrammatiko** [comment]
Try https://github.com/dgrammatiko/mod_child_export/releases/tag/v0.0.5

**Comment by PhocaCz** [comment]
Still the same:

```
{success: false, message: "The file at mod_childexport/helper.php does not exist.", messages: null,…}
data
: 
null
message
: 
"The file at mod_childexport/helper.php does not exist."
messages
: 
null
success
: 
false
```

**Comment by dgrammatiko** [comment]
Let me know if https://github.com/dgrammatiko/mod_child_export/releases/tag/v0.0.6 is working for you

**Comment by PhocaCz** [comment]
Great, now it is OK.

Now, a feature request:

Being able to export a child template is great, but for some it's missing something. If I want to send such a child template to other users who will install such a package, it would be great to add:

- Information that says during installation that a child template needs to be created

See here an example, I just did it in script.php (not sure if it is right, or not, the main task is to inform what to do in case of a missing child template):

https://github.com/PhocaCz/PhocaTemplates/releases/download/CassiopeiaPhocaCart/tmpl_child_cassiopeia_phocacart_v4.0.0.zip

![img](https://i.imgur.com/SgQb0Yp.png)

- Another feature (maybe problematic) could be some menu to create a child template if it doesn't exist, etc. etc.

 I know this is actually beyond the capabilities of the export feature, but if some standardized process (both export and installation) was created, it would be great. I have a solution myself, but I would like all developers to use a uniform standardized approach. Even though you wrote to me, and I know that child templates are not originally intended for installation, the practice is that there is such a request from users. Build a page on Cassiopeia, for example, and just install a minor change in the form of a child template.

Thank you.

**Comment by dgrammatiko** [comment]
> Information that says during installation that a child template needs to be created


Hell **NOOO**, that's not how things work. A child template **IS AN INSTALLABLE TEMPLATE** by definition. Users DO NOT have to create anything manually if they have the zip file.-

FWIW there is bug in the way Joomla handles the Ajax in the modules new structure, will open a PR suggesting a fix. 
Thanks for testing

**Comment by PhocaCz** [comment]
> > Information that says during installation that a child template needs to be created
> 
> Hell **NOOO**, that's not how things work. A child template **IS AN INSTALLABLE TEMPLATE** by definition. Users DO NOT have to create anything manually if they have the zip file.-

Maybe you don't understand me correctly. If I export my child template with this module and want to install it on other Joomla instance, I get following error:

![img](https://i.imgur.com/EK3VVWx.png)

But seems the warning message is somehow weird, it says: File already exists [ROOT]/templates/cassiopeia_phocacart/html ... but this is completely new instance and such folder does not exist.

**Comment by dgrammatiko** [comment]
> I get following error:

Can you send me the zip that produced this error?

**Comment by PhocaCz** [comment]
![img](https://i.imgur.com/hAxnfs0.png)



[cassiopeia_phocacart_v1.0.zip](https://github.com/dgrammatiko/mod_child_export/files/11462898/cassiopeia_phocacart_v1.0.zip)

**Comment by dgrammatiko** [comment]
Should be ok now, check https://github.com/dgrammatiko/mod_child_export/releases/tag/1.0.0

**Comment by PhocaCz** [comment]
1) Seems like empty folders produce problems
![img](https://i.imgur.com/51LXhiy.png)

2) And the question arises. Should the package get "upgrade" feature or not?

![img](https://i.imgur.com/AgO2NuD.png)

**Comment by PhocaCz** [comment]
Maybe, this could be option in the module (produce upgrade or not upgrade package):

```<extension type="template" client="site" method="upgrade">```
vs.:
```<extension type="template" client="site">```

**Comment by dgrammatiko** [comment]
> Seems like empty folders produce problems

Hmm, I thought that the zip had the empty folders

> And the question arises. Should the package get "upgrade" feature or not?

NOO. The error is correctly explaining that you CANNOT install over an existing template. Also upgrade means that it needs a server, etc which IS NOT what child templates are for, they are USER generated themes (ie user overrides).

**Comment by PhocaCz** [comment]
> NOO. The error is correctly explaining that you CANNOT install over an existing template. Also upgrade means that it needs a server, etc which IS NOT what child templates are for, they are USER generated themes (ie user overrides).

Yes, I understand but as I wrote, there are many examples in practice where child templates are used as a standard installation package (including upgrade function).

Like when developer produces installable child template package for end user and end user just wants to upgrade the child template on own instance (knowing that he/she will overwrite existing files, which in most cases he/she does not edit at all).

**Comment by dgrammatiko** [comment]
> there are many examples in practice where child templates are used as a standard installation package

These people SHOULD really reconsider what child templates ARE. They were created as a way to enable templates to SAFELY UPDATE without destroying USER's touched files. If you add upgrade into child templates then you have to reinvent a grandchild thing so ACTUAL USER touched files are not overridden by your update. Basically IT IS WRONG, and it's against any logic...

Anyways, I'm not going to add `method="upgrade"`, the repo is MIT so you might fork it and do whatever you want. I would like to just say just because you might be able to do something that doesn't mean that it's right (breaking the whole ecosystem is not a good idea)

**Comment by dgrammatiko** [comment]
You're ABUSING child templates. You should really distribute your OWN TEMPLATE

**Comment by PhocaCz** [comment]
This is Cassiopeia (child template):
https://www.phoca.cz/phocacartdemo/

Users ask me to share this customized Cassiopeia (child template), I can:

a) not abuse child template and send the users to ...
b) or abuse child template and share it to users as convenient for the users as possible

I chose b) and I'm just looking for the best way to make it easy for users to use this child template.

Of course, if there was own template, I would distribute this one, but there is no own template.

I'm not a template developer, I just made a child template for my purposes and some users would like to use it.

**Comment by dgrammatiko** [comment]
You should either
- Fork cassiopeia (it's OSS, eg I forked Atum to roll BS 5.3 and dark theme: https://muta.dgrammatiko.dev, Probably you should do the same)
- Not be nice to couple of  spoiled users and set a very bad example for the ecosystem.
- I ignore all of that mass distribute something that was designed to be USER GENERATED and then complain that Joomla is shit...

**Comment by PhocaCz** [comment]
As I wrote, I am not template developer and unfortunately have no time to maintain complete template. Child template give me the possibility to only add few lines of custom CSS (which basically will not need to be maintained for a long time) and I know that the user of such child template will have the template constantly updated and maintained.

Although I fully understand your arguments, in practice it turns out that even the child template distribution has its pros.

**Comment by brianteeman** [comment]
Very interesting discussion. I believe there is a very valid usecase for distributing child templates of cassiopeia and I have written an article about it that will be published this week in the JCM. It was written before this module was released.
